development:
  host: localhost
  database: ribbot_development

test:
  host: localhost
  database: ribbot_test

# set these environment variables on your prod server
production:
  host: localhost
#  port: 27017
#  username: admin
#  password: dbadminpwd
#  database: stories
  database: ribbot_development
#  host: <%= ENV['MONGOID_HOST'] %>
#  port: <%= ENV['MONGOID_PORT'] %>
#  username: <%= ENV['MONGOID_USERNAME'] %>
#  password: <%= ENV['MONGOID_PASSWORD'] %>
#  database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
